name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        IMAGE_TAG="genuineanger/pcc:$(date +%s)"
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        docker build . --file Dockerfile --tag $IMAGE_TAG

    - name: Verify Docker image
      run: |
        docker images | grep genuineanger/pcc

    - name: Push Docker image
      run: |
        docker push ${{ env.IMAGE_TAG }}
